# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 0 * * 0" # Wekelijkse scan op zondag om middernacht

permissions:
  contents: read
jobs:
  security-checks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest bandit safety

    # Lint the code
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    # Run tests
    - name: Test with pytest
      run: |
        pytest

    # Static Application Security Testing (SAST)
    - name: Security scan with Bandit
      run: |
        bandit -r . || exit 1

    # Dependency vulnerability check
    - name: Dependency scan with Safety
      run: |
        safety check --full-report || exit 1

    # Secrets detection
    - name: Scan for secrets
      uses: trufflesecurity/trufflehog-actions-scan@v3
      with:
        scan-directory: .

  # Block PRs with warnings or failures
  pull_request:
    if: ${{ failure() }}

